//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Sponsorships = new HashSet<Sponsorship>();
        }
    
        public string DeviceID { get; set; }
        public Nullable<int> DeviceCategory { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> DeviceSpecification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sponsorship> Sponsorships { get; set; }
        public virtual DeviceCategory DeviceCategory1 { get; set; }
        public virtual DeviceSpecification DeviceSpecification1 { get; set; }
    }
}
