//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int SponsorshipID { get; set; }
        public string User { get; set; }
        public string Device { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Location { get; set; }
        public string Note { get; set; }
    
        public virtual Device Device1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
